# Generated by Django 2.2.3 on 2019-07-12 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190712_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_by',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='created_by',
            new_name='created_on',
        ),
    ]
