# Generated by Django 2.2.3 on 2019-07-16 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190712_1022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ('-created_on',)},
        ),
    ]
