# Generated by Django 2.2.4 on 2019-09-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressmodel',
            name='postal_code',
            field=models.CharField(max_length=6),
        ),
    ]
