# Generated by Django 2.2.4 on 2019-09-06 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_auto_20190907_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressmodel',
            name='billing_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_model', to='billing.BillingProfile'),
        ),
    ]
