# Generated by Django 2.2.4 on 2019-09-10 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0006_auto_20190910_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addressmodel',
            old_name='address_types',
            new_name='address_type',
        ),
    ]
