# Generated by Django 2.2.4 on 2019-10-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0007_auto_20190911_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressmodel',
            name='country',
            field=models.CharField(choices=[('in', 'India'), ('us', 'United State America'), ('ban', 'Bangladesh'), ('sri', 'Sri Lanka')], max_length=50),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='state',
            field=models.CharField(choices=[('up', 'Uttar Pradesh'), ('del', 'Delhi'), ('ald', 'Allahabad')], max_length=50),
        ),
    ]
