# Generated by Django 2.2.4 on 2019-10-08 06:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0008_auto_20191008_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressmodel',
            name='district',
            field=models.CharField(choices=[('pbh', 'Pratapgarh'), ('ald', 'Allahabad'), ('lko', 'Lucknow'), ('kan', 'Kanpur'), ('ndls', 'New Delhi'), ('delw', 'New Delhi west')],max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='state',
            field=models.CharField(choices=[('up', 'Uttar Pradesh'), ('del', 'Delhi')], max_length=50),
        ),
    ]
