# Generated by Django 2.2.4 on 2019-10-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0009_auto_20191008_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressmodel',
            name='country',
            field=models.CharField(choices=[('india', 'India')], max_length=50),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='district',
            field=models.CharField(choices=[('pratapgarh', 'Pratapgarh'), ('allahabad', 'Allahabad'), ('lucknow', 'Lucknow'), ('kanpur', 'Kanpur'), ('new delhi', 'New Delhi')], max_length=40),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='state',
            field=models.CharField(choices=[('uttar pradesh', 'Uttar Pradesh'), ('delhi', 'Delhi')], max_length=50),
        ),
    ]
