# Generated by Django 2.2.4 on 2019-08-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
