# Generated by Django 2.2.4 on 2019-08-29 17:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20190828_0207'),
        ('orders', '0002_auto_20190825_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_billing_profile', to='billing.BillingProfile'),
            preserve_default=False,
        ),
    ]
