# Generated by Django 2.2.4 on 2019-08-29 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190829_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_billing_profile', to='billing.BillingProfile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
